version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tryirr
      POSTGRES_USER: tryirr
      POSTGRES_PASSWORD: tryirr
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn tryirr_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

