# Generated by Django 5.2.4 on 2025-07-25 03:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghasedak_api_key', models.CharField(max_length=255)),
                ('ghasedak_template_name', models.CharField(max_length=100)),
                ('mailgrid_api_key', models.CharField(max_length=255)),
                ('mailgrid_sender_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
