# Generated by Django 5.2 on 2025-07-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_kyc_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_document',
            field=models.FileField(blank=True, help_text='A scan or photo of your government‑issued ID.', null=True, upload_to='kyc/id_documents/'),
        ),
    ]
