# Generated by Django 5.2 on 2025-07-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer_trade_chatmessage_wallet'),
        ('core', '0002_sitesettings'),
    ]

    operations = [
    ]
