# Generated by Django 5.2 on 2025-07-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_address_document'),
        ('core', '0003_merge_20250724_0321'),
    ]

    operations = [
    ]
