# Generated by Django 5.2 on 2025-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_make_phone_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_document',
            field=models.FileField(blank=True, help_text='A scan or photo of your government‑issued ID.', null=True, upload_to='kyc/id_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selfie',
            field=models.FileField(blank=True, help_text='A selfie of you holding your ID next to your face.', null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission'),
        ),
    ]
