# Generated by Django 5.2 on 2025-07-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250724_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
